export enum SystemRoleEnum {
  ADMIN = "ADMIN",
  STUDENT = "STUDENT",
  TEACHER = "TEACHER",
  PARENT = "PARENT",
}

export enum AuthProviderEnum {
  LOCAL = "LOCAL",
  GOOGLE = "GOOGLE",
  MAGIC_LINK = "MAGIC_LINK",
}

export enum MagicLinkPurposeEnum {
  ACTIVATION = "ACTIVATION",
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
}

export enum NotificationTypeEnum {
  NEW_LEARNING_MODULE = "NEW_LEARNING_MODULE",
  MODULE_DEADLINE_SOON = "MODULE_DEADLINE_SOON",
  MODULE_DEADLINE_PASSED = "MODULE_DEADLINE_PASSED",
  FORUM_REPLY_TO_QUESTION = "FORUM_REPLY_TO_QUESTION",
  FORUM_REPLY_TO_ANSWER = "FORUM_REPLY_TO_ANSWER",
  STUDENT_FINISHED_MODULE = "STUDENT_FINISHED_MODULE",
}

export enum ModuleTypeEnum {
  SUBJECT = "SUBJECT",
  DIAGNOSTIC_TEST = "DIAGNOSTIC_TEST",
}
